[package]
name = "nsis-semvercompare"
version = "0.2.0"
authors = { workspace = true }
edition = { workspace = true }
license = { workspace = true }

[lib]
crate-type = ["rlib", "cdylib"]

[dependencies]
semver = "1.0"
pluginapi = { workspace = true }
windows-sys = { workspace = true }
